# Generated by Django 5.2.5 on 2025-09-30 13:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('specification', models.TextField(blank=True, null=True)),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
                ('thumbnail', models.URLField()),
                ('category', models.CharField(choices=[('JERSEY', 'Jersey'), ('SHORTS', 'Celana / Shorts'), ('SHOES', 'Sepatu Bola / Futsal'), ('GEAR', 'Aksesoris (Sarung Tangan, Shin Guard, dll)'), ('MERCH', 'Merchandise / Collectibles'), ('OTHERS', 'Lain-lain')], default='Jersey', max_length=100)),
                ('is_featured', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
