# Generated by Django 5.2.5 on 2025-09-13 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='spesification',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('JERSEY', 'Jersey'), ('SHORTS', 'Celana / Shorts'), ('SHOES', 'Sepatu Bola / Futsal'), ('GEAR', 'Aksesoris (Sarung Tangan, Shin Guard, dll)'), ('MERCH', 'Merchandise / Collectibles'), ('OTHERS', 'Lain-lain')], default='Jersey', max_length=100),
        ),
    ]
