# Generated by Django 5.2.5 on 2025-09-13 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_product_spesification_alter_product_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='spesification',
            new_name='specification',
        ),
    ]
